"""mailer.py — Builds and sends an HTML email with approved job listings."""

import html
import logging
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

logger = logging.getLogger(__name__)

SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587


# Source color mapping
SOURCE_COLORS = {
    "linkedin": "#0a66c2",
    "indeed": "#2164f3",
    "glassdoor": "#0caa41",
    "gupy": "#ff6b35",
}


def source_color_hex(source: str) -> str:
    """Return a hex color for the given job source."""
    return SOURCE_COLORS.get(source.lower(), "#666666")


def send_jobs_email(jobs: list[dict], config: dict) -> None:
    """Build an HTML email from approved jobs and send via Gmail SMTP.

    Raises RuntimeError if sending fails.
    """
    sender = config["email_sender"]
    password = config["email_app_password"]
    recipient = config["email_recipient"]

    date_str = datetime.now().strftime("%d/%m/%Y")
    subject = f"Job Hunter — {len(jobs)} jobs found ({date_str})"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = recipient
    msg.attach(MIMEText(_build_plaintext(jobs), "plain", "utf-8"))
    msg.attach(MIMEText(_build_html(jobs), "html", "utf-8"))

    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=30) as server:
            server.starttls()
            server.login(sender, password)
            server.sendmail(sender, [recipient], msg.as_string())
        logger.info("Email sent to %s (%d jobs)", recipient, len(jobs))
    except Exception as exc:
        logger.exception("Failed to send email")
        raise RuntimeError(f"Email send failed: {exc}") from exc


def _build_html(jobs: list[dict]) -> str:
    """Build the HTML email body."""
    date_str = datetime.now().strftime("%d/%m/%Y")
    esc = html.escape

    cards = []
    for job in jobs:
        source = job.get("source", "").lower()
        color = source_color_hex(source)
        source_label = esc(source.capitalize())
        title = esc(job.get("title", "No title"))
        company = esc(job.get("company", "Unknown company"))
        location = esc(job.get("location", ""))
        url = esc(job.get("url", "#"), quote=True)
        reason = esc(job.get("match_reason", ""))
        date_posted = job.get("date_posted", "")
        if date_posted and len(date_posted) >= 10:
            date_posted = esc(date_posted[:10])

        card = f"""
        <div style="border:1px solid #e0e0e0;border-radius:8px;padding:16px;margin-bottom:16px;background:#ffffff;">
          <h3 style="margin:0 0 6px 0;font-size:16px;">
            <a href="{url}" style="color:#0066cc;text-decoration:none;">
              {title}
            </a>
          </h3>
          <p style="margin:4px 0;color:#333;font-size:14px;">
            <strong>{company}</strong>
            &nbsp;&mdash;&nbsp;{location}
          </p>
          <p style="margin:4px 0;font-size:12px;color:#888;">
            <span style="background:{color};color:#fff;padding:2px 6px;border-radius:3px;font-size:11px;">{source_label}</span>
            &nbsp; Posted: {date_posted or 'N/A'}
          </p>
          {'' if not reason else f'<p style="margin:10px 0 0 0;padding:8px 10px;background:#f0f7ff;border-left:3px solid #0066cc;border-radius:0 4px 4px 0;font-size:13px;color:#333;"><strong>Reason:</strong> {reason}</p>'}
        </div>"""
        cards.append(card)

    cards_html = "\n".join(cards)
    job_count = len(jobs)
    plural = "s" if job_count != 1 else ""

    return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f5f5f5;font-family:Arial,Helvetica,sans-serif;">
  <div style="max-width:680px;margin:24px auto;padding:0 16px;">
    <div style="background:#ffffff;border-radius:8px;padding:24px 28px;margin-bottom:16px;border-bottom:3px solid #0066cc;">
      <h1 style="margin:0;font-size:22px;color:#1a1a1a;">Job Hunter</h1>
      <p style="margin:6px 0 0 0;color:#666;font-size:14px;">{date_str} &mdash; {job_count} relevant job{plural} found</p>
    </div>
    {cards_html}
    <p style="font-size:11px;color:#aaa;text-align:center;margin-top:24px;padding-bottom:16px;">
      Automatically generated by Job Hunter (Minimax Edition).
    </p>
  </div>
</body>
</html>"""


def _build_plaintext(jobs: list[dict]) -> str:
    """Build a plain-text fallback."""
    date_str = datetime.now().strftime("%d/%m/%Y")
    lines = [
        f"Job Hunter — {date_str}",
        f"{len(jobs)} job(s) found",
        "=" * 50,
        "",
    ]
    for i, job in enumerate(jobs, 1):
        lines += [
            f"{i}. {job.get('title', '')} @ {job.get('company', '')}",
            f"   Location: {job.get('location', '')}",
            f"   Link: {job.get('url', '')}",
        ]
        if job.get("match_reason"):
            lines.append(f"   Reason: {job['match_reason']}")
        lines.append("")
    lines.append("Automatically generated by Job Hunter (Minimax Edition).")
    return "\n".join(lines)
